version: "2"

run:
  timeout: 3m
linters:
  default: none
  enable:
    # stil
    - revive
    - whitespace

    # semantika / bugovi
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - bodyclose

    # bezbednost
    - gosec

issues:
  max-issues-per-linter: 0
